// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxemgubcssdngvejxoky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4ZW1ndWJjc3Nkbmd2ZWp4b2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODAwNjEsImV4cCI6MjA3MjY1NjA2MX0.rvckfHIzas5xuUzsNSaPpnKTg0A0YFFvTKaCueY5hqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});