name: Deploy Widget to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build main app
        run: npm run build

      - name: Build widget
        run: |
          echo "Building widget..."
          npx vite build --config vite.widget.config.ts
          echo "Widget build complete!"
          echo "Contents of dist/widget/:"
          ls -la dist/widget/ || echo "Widget dist directory not found"
          echo "Verifying widget files exist:"
          test -f dist/widget/culmas-widget.js && echo "✓ culmas-widget.js found" || echo "✗ culmas-widget.js missing"
          test -f dist/widget/culmas-widget.css && echo "✓ culmas-widget.css found" || echo "✗ culmas-widget.css missing"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4